# travis workflow:
# - static code + unit test after build (before_script)
# - run code coverage after build

cache:
  directories:
    - "node_modules"

language: node_js
node_js:
  - "8"
  - "6"
  - "4"

os:
  - linux
  - osx
  - windows

before_script: npm test
after_success: npm run coverage